# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: David Carter
description: Source files for portfolio
author:
  name: David Carter
  email: dajocarter@gmail.com

# Grunt handles images and assets.
exclude: ['_img', '_css', '_js', '_fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
#paginate: 0
#paginate_path: 'page:num'

# Markdown library
markdown: kramdown
kramdown:
  input: GFM
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: pygments

###### HOMEPAGE VARIABLES DIVIDED BY SECTION ######
hero:
  headline: David Carter
  description: I'm a Manila based <span>graphic designer</span>, <span>illustrator</span> and <span>webdesigner</span> creating awesome and effective visual identities for companies of all sizes around the globe. Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.

social:
- url: "//twitter.com/dajocarter"
  icon: ion-social-twitter
- url: "//linkedin.com/in/dajocarter"
  icon: ion-social-linkedin
- url: "//instagram.com/dajocarter"
  icon: ion-social-instagram
- url: "//github.com/dajocarter"
  icon: ion-social-octocat
- url: "mailto:dajocarter@gmail.com"
  icon: ion-email

menu:
- link: "#home"
  text: Home
- link: "//dajocarter.com/blog"
  text: Blog
- link: "#about"
  text: About
- link: "#resume"
  text: Resume
- link: "#portfolio"
  text: Portfolio
- link: "#testimonials"
  text: Testimonials
- link: "#contact"
  text: Contact

about:
  title: Contact Details
  contact:
  - name: David Carter
    content:
    - text: '@dajocarter'
      url: '//twitter.com/dajocarter'
    - text: dajocarter@gmail.com
      url: mailto:dajocarter@gmail.com
  buttons:
  - url: "#"
    icon: ion-ios-cloud-download
    text: Download Resume

resume:
- title: Education
  css_class: education
  items:
  - title: Northern Illinois University
    info: Master of Science in Mathematics
    date: 2013
  - title: California State University Northridge
    info: Bachelor of Science in Mathematics
    date: 2011
- title: Work
  css_class: work
  items:
  - title: Tribeswell LLC
    info: Lead Developer
    date: December 2014 - Present
    description:  Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. Nullam dictum felis eu pede mollis pretium.
  - title: Hanapin Marketing
    info: Front End Development Intern
    date: May 2014 - August 2014
    description:  This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat
- title: Skills
  css_class: skill
  items:
  - title: Javascript
    info: Angular JS, Meteor JS, Node JS, React JS, jQuery
    description: Working with Javascript is my favorite. I learned Angular through building the Necter app with the Ionic framework. I'm currently learning and building apps with Meteor. I plan to start working with React and learning more about Node. I've started to use Underscore since working with Meteor, but I've heard better things of Lodash so I plan to incorporate that into my workflow.
  - title: CSS
    info: Sass, CSS3
    description: I picked up Sass early on when I first started learning web development. Nesting rules is much more intuitive and easier to read and write with. I've recently been interested in Stylus so I can get rid of those pesky braces.
  - title: Wordpress
    info: PHP, ACF Pro, Scratch Theme
    description: At Tribeswell, we specialized in making custom Wordpress sites utilizing our own <a href="http://scratchtheme.com">Scratch Theme</a>. Some of the sites I personally worked on include <a href="http://kinsmendistillery.com">Kinsmen Distillery</a>, <a href="http://boydandcompany.com">Boyd and Company</a>, and <a href="http://lessonzest.com">Lesson Zest</a>.
  - title: Other Skills
    info: Git, Rails on Ruby, Grunt
    description: I use git for version control both professionally and personally. At Hanapin, I managed the front end of a Rails app. Grunt is my task runner of choice, but I'm going to try out Gulp when I start diving into Node. You can check out my Gruntfile <a href="#">here</a>.
  #- title:
    #skills:
      #- name: Photoshop
      #  level: 60

portfolio:
- title: "Necter"
  description: Hybrid Mobile App
  img: necter.jpg
  content: "It's Tinder for Groups. I built this on the Ionic framework for iOS and Android."
  tags: Branding, Web Development
  details: http://www.behance.net
- title: "Console"
  description: Web Development
  img: console.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Branding, Web Development
  details: http://www.behance.net
- title: "Judah"
  description: Webdesign
  img: judah.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Branding
  details: http://www.behance.net
- title: "Into The Light"
  description: Photography
  img: intothelight.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Photography
  details: http://www.behance.net
- title: "Farmer Boy"
  description: Branding
  img: farmerboy.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Branding, Webdesign
  details: http://www.behance.net
- title: "Girl"
  description: Photography
  img: girl.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Photography
  details: http://www.behance.net
- title: "Origami"
  description: Illustration
  img: origami.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Branding, Illustration
  details: http://www.behance.net
- title: "Retrocam"
  description: Web Development
  img: retrocam.jpg
  content: "Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit."
  tags: Webdesign, Photography
  details: http://www.behance.net

call:
  title: Get in Touch
  buttons:
  - text: Email Me Now
    url: mailto:dajocarter@gmail.com

testimonials:
  title: Testimonials
  quotes:
  - author: Steve Jobs
    content: Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.  If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.
  - author: Mr. Adobe
    content: This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.

contact:
  title: Contact Form
  menu: Contact
  lead: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.
  widgets:
    - title: Contact Details
      name: David Carter
      content:
        - text: '@dajocarter'
          url: '//twitter.com/dajocarter'
        - text: dajocarter@gmail.com
          url: mailto:dajocarter@gmail.com

copyright:
  - line: '&copy; Copyright 2014 CeeVee'
  - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>