# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

domain: http://localhost:3000
name: David Carter
description: Source files for portfolio
author:
  name: David Carter
  email: dajocarter@gmail.com

# Grunt handles images and assets.
exclude: ['_img', '_css', '_js', '_fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
#paginate: 0
#paginate_path: 'page:num'

# Markdown library
markdown: kramdown
kramdown:
  input: GFM
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: pygments

copyright:
  - line: '&copy; Copyright 2015 dajocarter'
  - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>